name: Copy Python Files

on:
  push:
    branches: [ main, workflow_copy_python_files ]
    paths:
      - '**/*.py'  # Trigger on any Python file change
  workflow_dispatch:  # Allow manual triggering

jobs:
  copy-files:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Create destination directory
      run: |
        if (-not (Test-Path -Path "C:\Users\DAK_Kumar\Documents\GIT_PYTHON")) {
          New-Item -ItemType Directory -Path "C:\Users\DAK_Kumar\Documents\GIT_PYTHON" -Force
        }
        
    - name: Copy Python files
      run: |
        # Find all Python files and copy them
        Get-ChildItem -Path ".\python_files" -Filter "*.py" -Recurse |
        ForEach-Object {
          $destination = Join-Path "C:\Users\DAK_Kumar\Documents\GIT_PYTHON" $_.Name
          Copy-Item -Path $_.FullName -Destination $destination -Force
        }
      shell: pwsh
